### ISSUE TITLE
Need a full example.py for a bird user.

### ISSUE THREAD

**Issue by tlze** [Boneflame/gpipe43#1]
Could you give a full example.py. I hope my gapps working at first.  and then I will learn more. sorry for my bad english. 
能给一个完整的example.py文件吗？我希望gapps运行起来先，之后再慢慢学习。
如果能建立列表，共享大家已经配置可用的源，将大大提高本项目面对的用户群。我就是其中之一，只会用，不会编程。

**Comment by Boneflame** [comment]
@tlze 已更新，用b站文章区做的例子。

建立列表有考虑过。以后会开个repo，大家共同维护。

**Comment by tlze** [comment]
谢谢
